name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master # Trigger this action on pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use Node.js 14.x version (adjust as necessary)

      - name: Install dependencies
        run: |
          npm install  # Install project dependencies

      - name: Build Next.js app
        run: |
          npm run build  # Run the Next.js build (you can adjust this if you're using a different build command)

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash  # Install Firebase CLI

      - name: Firebase Login
        uses: wzieba/Firebase-Action@v2
        with:
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }} # You can store your Firebase token in GitHub secrets

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project your-project-id  # Adjust for your Firebase project
