name: Deploy Next.js to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create .env.production
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(echo '${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}' | tr -d '\n' | tr -d '\r')" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}" >> .env.production

      - name: Lint .env.production file
        run: |
          echo "🔍 Linting .env.production..."
          cat .env.production | while IFS= read -r line; do
            if [[ "$line" =~ ^[^#=]+=[^=]+$ ]]; then
              echo "✅ Valid: $line"
            elif [[ -n "$line" && ! "$line" =~ ^# ]]; then
              echo "❌ Invalid env line: '$line'"
              exit 1
            fi
          done

      - name: Build Next.js app
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --force

      - name: Deploy Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions
